/*
 * system.h - SOPC Builder system and BSP software package information
 *
 * Machine generated for CPU 'nios2_cpu' in SOPC Builder design 'dvs22_g6_system'
 * SOPC Builder design path: ../../hardware/dvs22_g6_system.sopcinfo
 *
 * Generated: Thu Mar 10 15:16:49 CET 2022
 */

/*
 * DO NOT MODIFY THIS FILE
 *
 * Changing this file will have subtle consequences
 * which will almost certainly lead to a nonfunctioning
 * system. If you do modify this file, be aware that your
 * changes will be overwritten and lost when this file
 * is generated again.
 *
 * DO NOT MODIFY THIS FILE
 */

/*
 * License Agreement
 *
 * Copyright (c) 2008
 * Altera Corporation, San Jose, California, USA.
 * All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * This agreement shall be governed in all respects by the laws of the State
 * of California and by the laws of the United States of America.
 */

#ifndef __SYSTEM_H_
#define __SYSTEM_H_

/* Include definitions from linker script generator */
#include "linker.h"


/*
 * CPU configuration
 *
 */

#define ALT_CPU_ARCHITECTURE "altera_nios2_gen2"
#define ALT_CPU_BIG_ENDIAN 0
#define ALT_CPU_BREAK_ADDR 0x04000820
#define ALT_CPU_CPU_ARCH_NIOS2_R1
#define ALT_CPU_CPU_FREQ 50000000u
#define ALT_CPU_CPU_ID_SIZE 1
#define ALT_CPU_CPU_ID_VALUE 0x00000000
#define ALT_CPU_CPU_IMPLEMENTATION "tiny"
#define ALT_CPU_DATA_ADDR_WIDTH 0x1b
#define ALT_CPU_DCACHE_LINE_SIZE 0
#define ALT_CPU_DCACHE_LINE_SIZE_LOG2 0
#define ALT_CPU_DCACHE_SIZE 0
#define ALT_CPU_EXCEPTION_ADDR 0x02000020
#define ALT_CPU_FLASH_ACCELERATOR_LINES 0
#define ALT_CPU_FLASH_ACCELERATOR_LINE_SIZE 0
#define ALT_CPU_FLUSHDA_SUPPORTED
#define ALT_CPU_FREQ 50000000
#define ALT_CPU_HARDWARE_DIVIDE_PRESENT 0
#define ALT_CPU_HARDWARE_MULTIPLY_PRESENT 0
#define ALT_CPU_HARDWARE_MULX_PRESENT 0
#define ALT_CPU_HAS_DEBUG_CORE 1
#define ALT_CPU_HAS_DEBUG_STUB
#define ALT_CPU_HAS_ILLEGAL_INSTRUCTION_EXCEPTION
#define ALT_CPU_HAS_JMPI_INSTRUCTION
#define ALT_CPU_ICACHE_LINE_SIZE 0
#define ALT_CPU_ICACHE_LINE_SIZE_LOG2 0
#define ALT_CPU_ICACHE_SIZE 0
#define ALT_CPU_INST_ADDR_WIDTH 0x1b
#define ALT_CPU_NAME "nios2_cpu"
#define ALT_CPU_OCI_VERSION 1
#define ALT_CPU_RESET_ADDR 0x02000000


/*
 * CPU configuration (with legacy prefix - don't use these anymore)
 *
 */

#define NIOS2_BIG_ENDIAN 0
#define NIOS2_BREAK_ADDR 0x04000820
#define NIOS2_CPU_ARCH_NIOS2_R1
#define NIOS2_CPU_FREQ 50000000u
#define NIOS2_CPU_ID_SIZE 1
#define NIOS2_CPU_ID_VALUE 0x00000000
#define NIOS2_CPU_IMPLEMENTATION "tiny"
#define NIOS2_DATA_ADDR_WIDTH 0x1b
#define NIOS2_DCACHE_LINE_SIZE 0
#define NIOS2_DCACHE_LINE_SIZE_LOG2 0
#define NIOS2_DCACHE_SIZE 0
#define NIOS2_EXCEPTION_ADDR 0x02000020
#define NIOS2_FLASH_ACCELERATOR_LINES 0
#define NIOS2_FLASH_ACCELERATOR_LINE_SIZE 0
#define NIOS2_FLUSHDA_SUPPORTED
#define NIOS2_HARDWARE_DIVIDE_PRESENT 0
#define NIOS2_HARDWARE_MULTIPLY_PRESENT 0
#define NIOS2_HARDWARE_MULX_PRESENT 0
#define NIOS2_HAS_DEBUG_CORE 1
#define NIOS2_HAS_DEBUG_STUB
#define NIOS2_HAS_ILLEGAL_INSTRUCTION_EXCEPTION
#define NIOS2_HAS_JMPI_INSTRUCTION
#define NIOS2_ICACHE_LINE_SIZE 0
#define NIOS2_ICACHE_LINE_SIZE_LOG2 0
#define NIOS2_ICACHE_SIZE 0
#define NIOS2_INST_ADDR_WIDTH 0x1b
#define NIOS2_OCI_VERSION 1
#define NIOS2_RESET_ADDR 0x02000000


/*
 * Define for each module class mastered by the CPU
 *
 */

#define __ACC_BILINEAR_SCALING
#define __ALTERA_AVALON_JTAG_UART
#define __ALTERA_AVALON_NEW_SDRAM_CONTROLLER
#define __ALTERA_AVALON_PERFORMANCE_COUNTER
#define __ALTERA_AVALON_SGDMA
#define __ALTERA_NIOS2_GEN2
#define __ALTPLL


/*
 * System configuration
 *
 */

#define ALT_DEVICE_FAMILY "Cyclone IV E"
#define ALT_ENHANCED_INTERRUPT_API_PRESENT
#define ALT_IRQ_BASE NULL
#define ALT_LOG_PORT "/dev/null"
#define ALT_LOG_PORT_BASE 0x0
#define ALT_LOG_PORT_DEV null
#define ALT_LOG_PORT_TYPE ""
#define ALT_NUM_EXTERNAL_INTERRUPT_CONTROLLERS 0
#define ALT_NUM_INTERNAL_INTERRUPT_CONTROLLERS 1
#define ALT_NUM_INTERRUPT_CONTROLLERS 1
#define ALT_STDERR "/dev/jtag_uart"
#define ALT_STDERR_BASE 0x4001120
#define ALT_STDERR_DEV jtag_uart
#define ALT_STDERR_IS_JTAG_UART
#define ALT_STDERR_PRESENT
#define ALT_STDERR_TYPE "altera_avalon_jtag_uart"
#define ALT_STDIN "/dev/jtag_uart"
#define ALT_STDIN_BASE 0x4001120
#define ALT_STDIN_DEV jtag_uart
#define ALT_STDIN_IS_JTAG_UART
#define ALT_STDIN_PRESENT
#define ALT_STDIN_TYPE "altera_avalon_jtag_uart"
#define ALT_STDOUT "/dev/jtag_uart"
#define ALT_STDOUT_BASE 0x4001120
#define ALT_STDOUT_DEV jtag_uart
#define ALT_STDOUT_IS_JTAG_UART
#define ALT_STDOUT_PRESENT
#define ALT_STDOUT_TYPE "altera_avalon_jtag_uart"
#define ALT_SYSTEM_NAME "dvs22_g6_system"


/*
 * acc_bilinear_scaling configuration
 *
 */

#define ACC_BILINEAR_SCALING_BASE 0x4001110
#define ACC_BILINEAR_SCALING_IRQ -1
#define ACC_BILINEAR_SCALING_IRQ_INTERRUPT_CONTROLLER_ID -1
#define ACC_BILINEAR_SCALING_NAME "/dev/acc_bilinear_scaling"
#define ACC_BILINEAR_SCALING_SPAN 16
#define ACC_BILINEAR_SCALING_TYPE "acc_bilinear_scaling"
#define ALT_MODULE_CLASS_acc_bilinear_scaling acc_bilinear_scaling


/*
 * altera_hostfs configuration
 *
 */

#define ALTERA_HOSTFS_NAME "/mnt/host"


/*
 * hal configuration
 *
 */

#define ALT_INCLUDE_INSTRUCTION_RELATED_EXCEPTION_API
#define ALT_MAX_FD 32
#define ALT_SYS_CLK none
#define ALT_TIMESTAMP_CLK none


/*
 * jtag_uart configuration
 *
 */

#define ALT_MODULE_CLASS_jtag_uart altera_avalon_jtag_uart
#define JTAG_UART_BASE 0x4001120
#define JTAG_UART_IRQ 2
#define JTAG_UART_IRQ_INTERRUPT_CONTROLLER_ID 0
#define JTAG_UART_NAME "/dev/jtag_uart"
#define JTAG_UART_READ_DEPTH 64
#define JTAG_UART_READ_THRESHOLD 8
#define JTAG_UART_SPAN 8
#define JTAG_UART_TYPE "altera_avalon_jtag_uart"
#define JTAG_UART_WRITE_DEPTH 64
#define JTAG_UART_WRITE_THRESHOLD 8


/*
 * performance_counter configuration
 *
 */

#define ALT_MODULE_CLASS_performance_counter altera_avalon_performance_counter
#define PERFORMANCE_COUNTER_BASE 0x4001000
#define PERFORMANCE_COUNTER_HOW_MANY_SECTIONS 4
#define PERFORMANCE_COUNTER_IRQ -1
#define PERFORMANCE_COUNTER_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PERFORMANCE_COUNTER_NAME "/dev/performance_counter"
#define PERFORMANCE_COUNTER_SPAN 128
#define PERFORMANCE_COUNTER_TYPE "altera_avalon_performance_counter"


/*
 * pll configuration
 *
 */

#define ALT_MODULE_CLASS_pll altpll
#define PLL_BASE 0x4001100
#define PLL_IRQ -1
#define PLL_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PLL_NAME "/dev/pll"
#define PLL_SPAN 16
#define PLL_TYPE "altpll"


/*
 * sdram configuration
 *
 */

#define ALT_MODULE_CLASS_sdram altera_avalon_new_sdram_controller
#define SDRAM_BASE 0x2000000
#define SDRAM_CAS_LATENCY 3
#define SDRAM_CONTENTS_INFO
#define SDRAM_INIT_NOP_DELAY 0.0
#define SDRAM_INIT_REFRESH_COMMANDS 2
#define SDRAM_IRQ -1
#define SDRAM_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SDRAM_IS_INITIALIZED 1
#define SDRAM_NAME "/dev/sdram"
#define SDRAM_POWERUP_DELAY 100.0
#define SDRAM_REFRESH_PERIOD 15.625
#define SDRAM_REGISTER_DATA_IN 1
#define SDRAM_SDRAM_ADDR_WIDTH 0x18
#define SDRAM_SDRAM_BANK_WIDTH 2
#define SDRAM_SDRAM_COL_WIDTH 9
#define SDRAM_SDRAM_DATA_WIDTH 16
#define SDRAM_SDRAM_NUM_BANKS 4
#define SDRAM_SDRAM_NUM_CHIPSELECTS 1
#define SDRAM_SDRAM_ROW_WIDTH 13
#define SDRAM_SHARED_DATA 0
#define SDRAM_SIM_MODEL_BASE 0
#define SDRAM_SPAN 33554432
#define SDRAM_STARVATION_INDICATOR 0
#define SDRAM_TRISTATE_BRIDGE_SLAVE ""
#define SDRAM_TYPE "altera_avalon_new_sdram_controller"
#define SDRAM_T_AC 5.5
#define SDRAM_T_MRD 3
#define SDRAM_T_RCD 20.0
#define SDRAM_T_RFC 70.0
#define SDRAM_T_RP 20.0
#define SDRAM_T_WR 14.0


/*
 * sdram configuration as viewed by sgdma_in_m_read
 *
 */

#define SGDMA_IN_M_READ_SDRAM_BASE 0x2000000
#define SGDMA_IN_M_READ_SDRAM_CAS_LATENCY 3
#define SGDMA_IN_M_READ_SDRAM_CONTENTS_INFO
#define SGDMA_IN_M_READ_SDRAM_INIT_NOP_DELAY 0.0
#define SGDMA_IN_M_READ_SDRAM_INIT_REFRESH_COMMANDS 2
#define SGDMA_IN_M_READ_SDRAM_IRQ -1
#define SGDMA_IN_M_READ_SDRAM_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SGDMA_IN_M_READ_SDRAM_IS_INITIALIZED 1
#define SGDMA_IN_M_READ_SDRAM_NAME "/dev/sdram"
#define SGDMA_IN_M_READ_SDRAM_POWERUP_DELAY 100.0
#define SGDMA_IN_M_READ_SDRAM_REFRESH_PERIOD 15.625
#define SGDMA_IN_M_READ_SDRAM_REGISTER_DATA_IN 1
#define SGDMA_IN_M_READ_SDRAM_SDRAM_ADDR_WIDTH 0x18
#define SGDMA_IN_M_READ_SDRAM_SDRAM_BANK_WIDTH 2
#define SGDMA_IN_M_READ_SDRAM_SDRAM_COL_WIDTH 9
#define SGDMA_IN_M_READ_SDRAM_SDRAM_DATA_WIDTH 16
#define SGDMA_IN_M_READ_SDRAM_SDRAM_NUM_BANKS 4
#define SGDMA_IN_M_READ_SDRAM_SDRAM_NUM_CHIPSELECTS 1
#define SGDMA_IN_M_READ_SDRAM_SDRAM_ROW_WIDTH 13
#define SGDMA_IN_M_READ_SDRAM_SHARED_DATA 0
#define SGDMA_IN_M_READ_SDRAM_SIM_MODEL_BASE 0
#define SGDMA_IN_M_READ_SDRAM_SPAN 33554432
#define SGDMA_IN_M_READ_SDRAM_STARVATION_INDICATOR 0
#define SGDMA_IN_M_READ_SDRAM_TRISTATE_BRIDGE_SLAVE ""
#define SGDMA_IN_M_READ_SDRAM_TYPE "altera_avalon_new_sdram_controller"
#define SGDMA_IN_M_READ_SDRAM_T_AC 5.5
#define SGDMA_IN_M_READ_SDRAM_T_MRD 3
#define SGDMA_IN_M_READ_SDRAM_T_RCD 20.0
#define SGDMA_IN_M_READ_SDRAM_T_RFC 70.0
#define SGDMA_IN_M_READ_SDRAM_T_RP 20.0
#define SGDMA_IN_M_READ_SDRAM_T_WR 14.0


/*
 * sdram configuration as viewed by sgdma_out_m_write
 *
 */

#define SGDMA_OUT_M_WRITE_SDRAM_BASE 0x2000000
#define SGDMA_OUT_M_WRITE_SDRAM_CAS_LATENCY 3
#define SGDMA_OUT_M_WRITE_SDRAM_CONTENTS_INFO
#define SGDMA_OUT_M_WRITE_SDRAM_INIT_NOP_DELAY 0.0
#define SGDMA_OUT_M_WRITE_SDRAM_INIT_REFRESH_COMMANDS 2
#define SGDMA_OUT_M_WRITE_SDRAM_IRQ -1
#define SGDMA_OUT_M_WRITE_SDRAM_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SGDMA_OUT_M_WRITE_SDRAM_IS_INITIALIZED 1
#define SGDMA_OUT_M_WRITE_SDRAM_NAME "/dev/sdram"
#define SGDMA_OUT_M_WRITE_SDRAM_POWERUP_DELAY 100.0
#define SGDMA_OUT_M_WRITE_SDRAM_REFRESH_PERIOD 15.625
#define SGDMA_OUT_M_WRITE_SDRAM_REGISTER_DATA_IN 1
#define SGDMA_OUT_M_WRITE_SDRAM_SDRAM_ADDR_WIDTH 0x18
#define SGDMA_OUT_M_WRITE_SDRAM_SDRAM_BANK_WIDTH 2
#define SGDMA_OUT_M_WRITE_SDRAM_SDRAM_COL_WIDTH 9
#define SGDMA_OUT_M_WRITE_SDRAM_SDRAM_DATA_WIDTH 16
#define SGDMA_OUT_M_WRITE_SDRAM_SDRAM_NUM_BANKS 4
#define SGDMA_OUT_M_WRITE_SDRAM_SDRAM_NUM_CHIPSELECTS 1
#define SGDMA_OUT_M_WRITE_SDRAM_SDRAM_ROW_WIDTH 13
#define SGDMA_OUT_M_WRITE_SDRAM_SHARED_DATA 0
#define SGDMA_OUT_M_WRITE_SDRAM_SIM_MODEL_BASE 0
#define SGDMA_OUT_M_WRITE_SDRAM_SPAN 33554432
#define SGDMA_OUT_M_WRITE_SDRAM_STARVATION_INDICATOR 0
#define SGDMA_OUT_M_WRITE_SDRAM_TRISTATE_BRIDGE_SLAVE ""
#define SGDMA_OUT_M_WRITE_SDRAM_TYPE "altera_avalon_new_sdram_controller"
#define SGDMA_OUT_M_WRITE_SDRAM_T_AC 5.5
#define SGDMA_OUT_M_WRITE_SDRAM_T_MRD 3
#define SGDMA_OUT_M_WRITE_SDRAM_T_RCD 20.0
#define SGDMA_OUT_M_WRITE_SDRAM_T_RFC 70.0
#define SGDMA_OUT_M_WRITE_SDRAM_T_RP 20.0
#define SGDMA_OUT_M_WRITE_SDRAM_T_WR 14.0


/*
 * sgdma_in configuration
 *
 */

#define ALT_MODULE_CLASS_sgdma_in altera_avalon_sgdma
#define SGDMA_IN_ADDRESS_WIDTH 32
#define SGDMA_IN_ALWAYS_DO_MAX_BURST 1
#define SGDMA_IN_ATLANTIC_CHANNEL_DATA_WIDTH 4
#define SGDMA_IN_AVALON_MM_BYTE_REORDER_MODE 0
#define SGDMA_IN_BASE 0x40010c0
#define SGDMA_IN_BURST_DATA_WIDTH 8
#define SGDMA_IN_BURST_TRANSFER 0
#define SGDMA_IN_BYTES_TO_TRANSFER_DATA_WIDTH 16
#define SGDMA_IN_CHAIN_WRITEBACK_DATA_WIDTH 32
#define SGDMA_IN_COMMAND_FIFO_DATA_WIDTH 104
#define SGDMA_IN_CONTROL_DATA_WIDTH 8
#define SGDMA_IN_CONTROL_SLAVE_ADDRESS_WIDTH 0x4
#define SGDMA_IN_CONTROL_SLAVE_DATA_WIDTH 32
#define SGDMA_IN_DESCRIPTOR_READ_BURST 0
#define SGDMA_IN_DESC_DATA_WIDTH 32
#define SGDMA_IN_HAS_READ_BLOCK 1
#define SGDMA_IN_HAS_WRITE_BLOCK 0
#define SGDMA_IN_IN_ERROR_WIDTH 0
#define SGDMA_IN_IRQ 1
#define SGDMA_IN_IRQ_INTERRUPT_CONTROLLER_ID 0
#define SGDMA_IN_NAME "/dev/sgdma_in"
#define SGDMA_IN_OUT_ERROR_WIDTH 0
#define SGDMA_IN_READ_BLOCK_DATA_WIDTH 8
#define SGDMA_IN_READ_BURSTCOUNT_WIDTH 4
#define SGDMA_IN_SPAN 64
#define SGDMA_IN_STATUS_TOKEN_DATA_WIDTH 24
#define SGDMA_IN_STREAM_DATA_WIDTH 8
#define SGDMA_IN_SYMBOLS_PER_BEAT 1
#define SGDMA_IN_TYPE "altera_avalon_sgdma"
#define SGDMA_IN_UNALIGNED_TRANSFER 0
#define SGDMA_IN_WRITE_BLOCK_DATA_WIDTH 8
#define SGDMA_IN_WRITE_BURSTCOUNT_WIDTH 4


/*
 * sgdma_out configuration
 *
 */

#define ALT_MODULE_CLASS_sgdma_out altera_avalon_sgdma
#define SGDMA_OUT_ADDRESS_WIDTH 32
#define SGDMA_OUT_ALWAYS_DO_MAX_BURST 1
#define SGDMA_OUT_ATLANTIC_CHANNEL_DATA_WIDTH 4
#define SGDMA_OUT_AVALON_MM_BYTE_REORDER_MODE 0
#define SGDMA_OUT_BASE 0x4001080
#define SGDMA_OUT_BURST_DATA_WIDTH 8
#define SGDMA_OUT_BURST_TRANSFER 0
#define SGDMA_OUT_BYTES_TO_TRANSFER_DATA_WIDTH 16
#define SGDMA_OUT_CHAIN_WRITEBACK_DATA_WIDTH 32
#define SGDMA_OUT_COMMAND_FIFO_DATA_WIDTH 104
#define SGDMA_OUT_CONTROL_DATA_WIDTH 8
#define SGDMA_OUT_CONTROL_SLAVE_ADDRESS_WIDTH 0x4
#define SGDMA_OUT_CONTROL_SLAVE_DATA_WIDTH 32
#define SGDMA_OUT_DESCRIPTOR_READ_BURST 0
#define SGDMA_OUT_DESC_DATA_WIDTH 32
#define SGDMA_OUT_HAS_READ_BLOCK 0
#define SGDMA_OUT_HAS_WRITE_BLOCK 1
#define SGDMA_OUT_IN_ERROR_WIDTH 0
#define SGDMA_OUT_IRQ 0
#define SGDMA_OUT_IRQ_INTERRUPT_CONTROLLER_ID 0
#define SGDMA_OUT_NAME "/dev/sgdma_out"
#define SGDMA_OUT_OUT_ERROR_WIDTH 0
#define SGDMA_OUT_READ_BLOCK_DATA_WIDTH 8
#define SGDMA_OUT_READ_BURSTCOUNT_WIDTH 4
#define SGDMA_OUT_SPAN 64
#define SGDMA_OUT_STATUS_TOKEN_DATA_WIDTH 24
#define SGDMA_OUT_STREAM_DATA_WIDTH 8
#define SGDMA_OUT_SYMBOLS_PER_BEAT 1
#define SGDMA_OUT_TYPE "altera_avalon_sgdma"
#define SGDMA_OUT_UNALIGNED_TRANSFER 0
#define SGDMA_OUT_WRITE_BLOCK_DATA_WIDTH 8
#define SGDMA_OUT_WRITE_BURSTCOUNT_WIDTH 4

#endif /* __SYSTEM_H_ */
