# TCL File Generated by Component Editor 20.1
# Mon Mar 14 10:13:39 CET 2022
# DO NOT MODIFY


# 
# bilinear_scaling "bilinear_scaling" v0.1
#  2022.03.14.10:13:39
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module bilinear_scaling
# 
set_module_property DESCRIPTION ""
set_module_property NAME bilinear_scaling
set_module_property VERSION 0.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME bilinear_scaling
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL new_component
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file new_component.vhd VHDL PATH new_component.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point scaling_coeffs
# 
add_interface scaling_coeffs avalon end
set_interface_property scaling_coeffs addressUnits SYMBOLS
set_interface_property scaling_coeffs associatedClock clk
set_interface_property scaling_coeffs associatedReset reset
set_interface_property scaling_coeffs bitsPerSymbol 8
set_interface_property scaling_coeffs burstOnBurstBoundariesOnly false
set_interface_property scaling_coeffs burstcountUnits WORDS
set_interface_property scaling_coeffs explicitAddressSpan 0
set_interface_property scaling_coeffs holdTime 0
set_interface_property scaling_coeffs linewrapBursts false
set_interface_property scaling_coeffs maximumPendingReadTransactions 0
set_interface_property scaling_coeffs maximumPendingWriteTransactions 0
set_interface_property scaling_coeffs readLatency 0
set_interface_property scaling_coeffs readWaitTime 1
set_interface_property scaling_coeffs setupTime 0
set_interface_property scaling_coeffs timingUnits Cycles
set_interface_property scaling_coeffs writeWaitTime 0
set_interface_property scaling_coeffs ENABLED true
set_interface_property scaling_coeffs EXPORT_OF ""
set_interface_property scaling_coeffs PORT_NAME_MAP ""
set_interface_property scaling_coeffs CMSIS_SVD_VARIABLES ""
set_interface_property scaling_coeffs SVD_ADDRESS_GROUP ""

add_interface_port scaling_coeffs scaling_coeffs_address address Input 1
add_interface_port scaling_coeffs scaling_coeffs_read read Input 1
add_interface_port scaling_coeffs scaling_coeffs_write write Input 1
add_interface_port scaling_coeffs scaling_coeffs_readdata readdata Output 8
add_interface_port scaling_coeffs scaling_coeffs_writedata writedata Input 8
add_interface_port scaling_coeffs scaling_coeffs_waitrequest waitrequest Output 1
set_interface_assignment scaling_coeffs embeddedsw.configuration.isFlash 0
set_interface_assignment scaling_coeffs embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment scaling_coeffs embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment scaling_coeffs embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point input_data
# 
add_interface input_data avalon_streaming end
set_interface_property input_data associatedClock clk
set_interface_property input_data associatedReset reset
set_interface_property input_data dataBitsPerSymbol 8
set_interface_property input_data errorDescriptor ""
set_interface_property input_data firstSymbolInHighOrderBits true
set_interface_property input_data maxChannel 0
set_interface_property input_data readyLatency 0
set_interface_property input_data ENABLED true
set_interface_property input_data EXPORT_OF ""
set_interface_property input_data PORT_NAME_MAP ""
set_interface_property input_data CMSIS_SVD_VARIABLES ""
set_interface_property input_data SVD_ADDRESS_GROUP ""

add_interface_port input_data asi_input_data_data data Input 8
add_interface_port input_data asi_input_data_valid valid Input 1
add_interface_port input_data asi_input_data_ready ready Output 1
add_interface_port input_data asi_input_data_sop startofpacket Input 1
add_interface_port input_data asi_input_data_eop endofpacket Input 1


# 
# connection point output_data
# 
add_interface output_data avalon_streaming start
set_interface_property output_data associatedClock clk
set_interface_property output_data dataBitsPerSymbol 8
set_interface_property output_data errorDescriptor ""
set_interface_property output_data firstSymbolInHighOrderBits true
set_interface_property output_data maxChannel 0
set_interface_property output_data readyLatency 0
set_interface_property output_data ENABLED true
set_interface_property output_data EXPORT_OF ""
set_interface_property output_data PORT_NAME_MAP ""
set_interface_property output_data CMSIS_SVD_VARIABLES ""
set_interface_property output_data SVD_ADDRESS_GROUP ""

add_interface_port output_data aso_output_data_data data Output 8
add_interface_port output_data aso_output_data_endofpacket endofpacket Output 1
add_interface_port output_data aso_output_data_startofpacket startofpacket Output 1
add_interface_port output_data aso_output_data_valid valid Output 1
add_interface_port output_data aso_output_data_ready ready Input 1

